version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.6.0
    steps:
      - checkout
      - run:
        name: Java
        command: 'sudo apt-get update && sudo apt install -t jessie-backports openjdk-8-jre-headless ca-certificates-java'
      - run:
          name: node version && npm version
          command: 'node -v && npm -v'
      - run:
          name: install-npm-vue
          command: npm install
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'