version: 2
jobs:
  build:
    docker:
      - image: timestep/farseek:0.0.1
    steps:
      - checkout
      - run:
          name: node version && npm version
          command: 'node -v && npm -v'
      - run:
          name: install-npm-vue
          command: npm install
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'