version: 2
jobs:
  build:
    docker:
        - image: timestep/farseek:0.0.4
        - image: selenium/standalone-chrome:latest
    steps:
        - checkout
        - run:
            name: node version && npm version
            command: 'node -v && npm -v'
        - run:
            name: install-npm-vue
            command: npm install
        - run:
            name: unit-test
            command: npm run unit
        - run:
            name: Running X virtual framebuffer
            command: xvfb -ac :99 -screen 0 1280x1024x16 +extension RANDR &
        - run:
            name: e2e-test
            command: npm run e2e
        - run:
            name: code-coverage
            command: './node_modules/.bin/nyc report --reporter=text-lcov'